### ISSUE TITLE
 The page you were looking for doesn't exist, getting 404. in root URL when using docker and docker-compose for building hyku

### ISSUE THREAD

**Issue by hydrosIII** [samvera-labs/hyku#1503] opened 2017-11-11 11:04 UTC
I have tried to start hyku with docker compose. Everything seems to be fine but when trying to load the page in localhost:8080 i just get a 404. 

Tested with: 
Docker 

 version 17.10.0-ce -Debian 9
and 
17.07.0-ce - Arch linux.

Strangely enough Hyku was working for me in my linux laptop last week. Or at least i could see a homepage. Has something changed since?

Steps to replicate:

Just run docker-compose up and wait, until it finishes. Then try to log in to localhost:8080 or the ip of the docker hyku_web container.

These are the last lines of the log, concerning the http request:
```
web_1             | I, [2017-11-11T10:46:10.346129 #6]  INFO -- : [5656718f-8ceb-4724-bf31-64c112b36b72] Started GET "/" for 189.216.98.86 at 2017-11-11 10:46:10 +0000
web_1             | I, [2017-11-11T10:46:10.348963 #6]  INFO -- : [5656718f-8ceb-4724-bf31-64c112b36b72] ActiveFedora: loading fedora config from /data/config/fedora.yml
web_1             | I, [2017-11-11T10:46:10.353688 #6]  INFO -- : [5656718f-8ceb-4724-bf31-64c112b36b72] ActiveFedora: loading solr config from /data/config/solr.yml
web_1             | D, [2017-11-11T10:46:10.425109 #6] DEBUG -- : [5656718f-8ceb-4724-bf31-64c112b36b72]   Account Load (0.8ms)  SELECT  "public"."accounts".* FROM "public"."accounts" WHERE "public"."accounts"."cname" = $1 LIMIT $2  [["cname", "45.63.115.89"], ["LIMIT", 1]]
web_1             | I, [2017-11-11T10:46:10.469748 #6]  INFO -- : [5656718f-8ceb-4724-bf31-64c112b36b72] Processing by Hyrax::HomepageController#index as HTML
web_1             | D, [2017-11-11T10:46:10.610701 #6] DEBUG -- : [5656718f-8ceb-4724-bf31-64c112b36b72] Usergroups are ["public"]
web_1             | D, [2017-11-11T10:46:10.620200 #6] DEBUG -- : [5656718f-8ceb-4724-bf31-64c112b36b72]   Hyrax::Feature Load (1.0ms)  SELECT  "hyrax_features".* FROM "hyrax_features" WHERE "hyrax_features"."key" = $1 ORDER BY "hyrax_features"."id" ASC LIMIT $2  [["key", "transfer_works"], ["LIMIT", 1]]
web_1             | D, [2017-11-11T10:46:10.622276 #6] DEBUG -- : [5656718f-8ceb-4724-bf31-64c112b36b72]   Hyrax::Feature Load (0.4ms)  SELECT  "hyrax_features".* FROM "hyrax_features" WHERE "hyrax_features"."key" = $1 ORDER BY "hyrax_features"."id" ASC LIMIT $2  [["key", "proxy_deposit"], ["LIMIT", 1]]
web_1             | D, [2017-11-11T10:46:10.646082 #6] DEBUG -- : [5656718f-8ceb-4724-bf31-64c112b36b72]    (2.7ms)  SELECT DISTINCT admin_set_id FROM "permission_template_accesses" INNER JOIN "permission_templates" ON "permission_templates"."id" = "permission_template_accesses"."permission_template_id" WHERE ("permission_template_accesses"."agent_type" = $1 AND "permission_template_accesses"."agent_id" = $2 AND "permission_template_accesses"."access" = 'manage' OR "permission_template_accesses"."agent_type" = $3 AND "permission_template_accesses"."agent_id" = 'public' AND "permission_template_accesses"."access" = 'manage')  [["agent_type", "user"], ["agent_id", ""], ["agent_type", "group"]]
web_1             | D, [2017-11-11T10:46:11.041036 #6] DEBUG -- : [5656718f-8ceb-4724-bf31-64c112b36b72]   CACHE Account Load (0.0ms)  SELECT  "public"."accounts".* FROM "public"."accounts" WHERE "public"."accounts"."cname" = $1 LIMIT $2  [["cname", "45.63.115.89"], ["LIMIT", 1]]
web_1             | I, [2017-11-11T10:46:11.086232 #6]  INFO -- : [5656718f-8ceb-4724-bf31-64c112b36b72] Completed 404 Not Found in 616ms (ActiveRecord: 31.7ms)
web_1             | F, [2017-11-11T10:46:11.088393 #6] FATAL -- : [5656718f-8ceb-4724-bf31-64c112b36b72]   
web_1             | F, [2017-11-11T10:46:11.088506 #6] FATAL -- : [5656718f-8ceb-4724-bf31-64c112b36b72] ActionController::RoutingError (Not Found):
web_1             | F, [2017-11-11T10:46:11.088846 #6] FATAL -- : [5656718f-8ceb-4724-bf31-64c112b36b72]   
web_1             | F, [2017-11-11T10:46:11.089149 #6] FATAL -- : [5656718f-8ceb-4724-bf31-64c112b36b72] app/controllers/application_controller.rb:27:in `block in <class:ApplicationController>'
web_1             | E, [2017-11-11T10:46:11.101170 #6] ERROR -- : ** [Honeybadger] Unable to send error report: API key is missing. id=e6127674-23b4-4d7b-bd09-9ecf3ea2ae2f level=3 pid=6
web_1             | I, [2017-11-11T10:47:02.374796 #6]  INFO -- : [56793272-5d6e-4223-bb57-23d5d50d7437] Started GET "/" for 189.216.98.86 at 2017-11-11 10:47:02 +0000
web_1             | D, [2017-11-11T10:47:02.387204 #6] DEBUG -- : [56793272-5d6e-4223-bb57-23d5d50d7437]   Account Load (1.7ms)  SELECT  "public"."accounts".* FROM "public"."accounts" WHERE "public"."accounts"."cname" = $1 LIMIT $2  [["cname", "45.63.115.89"], ["LIMIT", 1]]
web_1             | I, [2017-11-11T10:47:02.392725 #6]  INFO -- : [56793272-5d6e-4223-bb57-23d5d50d7437] Processing by Hyrax::HomepageController#index as HTML
web_1             | D, [2017-11-11T10:47:02.399324 #6] DEBUG -- : [56793272-5d6e-4223-bb57-23d5d50d7437] Usergroups are ["public"]
web_1             | D, [2017-11-11T10:47:02.405392 #6] DEBUG -- : [56793272-5d6e-4223-bb57-23d5d50d7437]   Hyrax::Feature Load (0.9ms)  SELECT  "hyrax_features".* FROM "hyrax_features" WHERE "hyrax_features"."key" = $1 ORDER BY "hyrax_features"."id" ASC LIMIT $2  [["key", "transfer_works"], ["LIMIT", 1]]
web_1             | D, [2017-11-11T10:47:02.407972 #6] DEBUG -- : [56793272-5d6e-4223-bb57-23d5d50d7437]   Hyrax::Feature Load (0.6ms)  SELECT  "hyrax_features".* FROM "hyrax_features" WHERE "hyrax_features"."key" = $1 ORDER BY "hyrax_features"."id" ASC LIMIT $2  [["key", "proxy_deposit"], ["LIMIT", 1]]
web_1             | D, [2017-11-11T10:47:02.413612 #6] DEBUG -- : [56793272-5d6e-4223-bb57-23d5d50d7437]    (1.2ms)  SELECT DISTINCT admin_set_id FROM "permission_template_accesses" INNER JOIN "permission_templates" ON "permission_templates"."id" = "permission_template_accesses"."permission_template_id" WHERE ("permission_template_accesses"."agent_type" = $1 AND "permission_template_accesses"."agent_id" = $2 AND "permission_template_accesses"."access" = 'manage' OR "permission_template_accesses"."agent_type" = $3 AND "permission_template_accesses"."agent_id" = 'public' AND "permission_template_accesses"."access" = 'manage')  [["agent_type", "user"], ["agent_id", ""], ["agent_type", "group"]]
web_1             | D, [2017-11-11T10:47:02.415857 #6] DEBUG -- : [56793272-5d6e-4223-bb57-23d5d50d7437]   CACHE Account Load (0.0ms)  SELECT  "public"."accounts".* FROM "public"."accounts" WHERE "public"."accounts"."cname" = $1 LIMIT $2  [["cname", "45.63.115.89"], ["LIMIT", 1]]
web_1             | I, [2017-11-11T10:47:02.422980 #6]  INFO -- : [56793272-5d6e-4223-bb57-23d5d50d7437] Completed 404 Not Found in 29ms (ActiveRecord: 3.2ms)
web_1             | F, [2017-11-11T10:47:02.425390 #6] FATAL -- : [56793272-5d6e-4223-bb57-23d5d50d7437]   
web_1             | F, [2017-11-11T10:47:02.425506 #6] FATAL -- : [56793272-5d6e-4223-bb57-23d5d50d7437] ActionController::RoutingError (Not Found):
web_1             | F, [2017-11-11T10:47:02.425989 #6] FATAL -- : [56793272-5d6e-4223-bb57-23d5d50d7437]   
web_1             | F, [2017-11-11T10:47:02.426076 #6] FATAL -- : [56793272-5d6e-4223-bb57-23d5d50d7437] app/controllers/application_controller.rb:27:in `block in <class:ApplicationController>'
web_1             | E, [2017-11-11T10:47:02.441846 #6] ERROR -- : ** [Honeybadger] Unable to send error report: API key is missing. id=57431752-6407-4859-85e8-ba2a9d379ca1 level=3 pid=6
```

**Comment by mjgiarlo** [comment] 2017-11-13 18:51
@hydrosIII What does `docker-compose ps` look like?

**Comment by hydrosIII** [comment] 2017-11-16 06:58
´´´
WARNING: The JAVA_OPTS variable is not set. Defaulting to a blank string.
        Name                       Command               State                            Ports                        
-----------------------------------------------------------------------------------------------------------------------
hyku_app_1              irb                              Exit 0                                                        
hyku_db_1               docker-entrypoint.sh postgres    Up       5432/tcp                                             
hyku_db_migrate_1       bundle exec rails db:migrate     Up       3000/tcp                                             
hyku_fcrepo_1           catalina.sh run                  Up       8080/tcp                                             
hyku_initialize_app_1   bundle exec rails zookeepe ...   Up       3000/tcp                                             
hyku_lb_1               /sbin/tini -- dockercloud- ...   Up       1936/tcp, 0.0.0.0:8443->443/tcp, 0.0.0.0:8080->80/tcp
hyku_memcache_1         docker-entrypoint.sh memcached   Up       11211/tcp                                            
hyku_redis_1            docker-entrypoint.sh redis ...   Up       6379/tcp                                             
hyku_solr_1             docker-entrypoint.sh solr  ...   Up       8983/tcp                                             
hyku_web_1              bash -c rm -f tmp/pids/ser ...   Up       3000/tcp                                             
hyku_workers_1          bundle exec sidekiq              Up       3000/tcp                                             
hyku_zoo1_1             /docker-entrypoint.sh zkSe ...   Up       2181/tcp, 2888/tcp, 3888/tcp                         
hyku_zoo2_1             /docker-entrypoint.sh zkSe ...   Up       2181/tcp, 2888/tcp, 3888/tcp                         
hyku_zoo3_1             /docker-entrypoint.sh zkSe ...   Up       2181/tcp, 2888/tcp, 3888/tcp   

´´´
Maybe its the line about the Java opts, i have seen it referenced in another bug.

**Comment by mjgiarlo** [comment] 2017-11-16 16:44
@hydrosIII I see the JAVA_OPTS warning too and the stack works OK for me. I'm not necessarily concerned about the warning.

You're right, the stack looks like it's up just fine and your HTTP request is clearly being routed to the application. The `RoutingNotFound` error is bizarre. Is there any more information in `log/production.log` within the `hyku_web_1` container? I assume you've tried taking the stack down and restarting it? If there's no data in it you care about, you can also try rebuilding it.

**Comment by hydrosIII** [comment] 2017-11-16 16:49
Hi, can you post your config for a working stack ? Let me check inside the hyku_web container, i suspect a RAM error. Maybe i need more ram or something. I have tried rebuilding it several times, and also tried it builiding in another OS. (Debian).

**Comment by hydrosIII** [comment] 2017-11-16 17:14
Hi, here are the logs found in development.log in the /data/log folder within hyku_web. Maybe change from dev to production. ? Anyways it is just plain docker, no additional config added. It is not working. Here are the logs:

```
Registering Local QA authority: licenses - Qa::Authorities::Local::FileBasedAuthority
Registering Local QA authority: resource_types - Qa::Authorities::Local::FileBasedAuthority
Registering Local QA authority: rights_statements - Qa::Authorities::Local::FileBasedAuthority
Registering Local QA authority: subjects - Qa::Authorities::Local::TableBasedAuthority
Registering Local QA authority: languages - Qa::Authorities::Local::TableBasedAuthority
Registering Local QA authority: genres - Qa::Authorities::Local::TableBasedAuthority
DEPRECATION WARNING: ActiveSupport.halt_callback_chains_on_return_false= is deprecated and will be removed in Rails 5.2. (called from <top (required)> at /data/config/initializers/new_framework_defaults.rb:17)
Hyrax::Engine.after_initialize - unable to persist registered roles.
It is expected during the application installation - during integration tests, rails install.
It is UNEXPECTED if you are booting up a Hyrax powered application via `rails server'
** [Honeybadger] Initializing Honeybadger Error Tracker for Ruby. Ship it! version=3.1.2 framework=rails level=1 pid=7
** [Honeybadger] Entering development mode: data will not be reported. level=2 pid=7
```

**Comment by mjgiarlo** [comment] 2017-11-16 17:18
@hydrosIII OK. Nothing too interesting there. Have you tried taking the containers down and rebuilding them yet?

**Comment by hydrosIII** [comment] 2017-11-16 17:26
Several Times. Even cleaned all the volumes, o have just tried it now. I will point out that the computer has only 4g of RAM. Maybe it needs more since it start several services? Its the only thing i can think of. Also i double checked that i was on sync with lattest comit in master branch.  

docker version 

Server:
 Version:      17.07.0-ce
 API version:  1.31 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   87847530f7
 Built:        Wed Aug 30 23:32:01 2017
 OS/Arch:      linux/amd64
 Experimental: false

Maybe its too much for  the "ship everywhere" docker catchphrase.

**Comment by hydrosIII** [comment] 2017-11-16 17:29
I will definitely try later on with a server with more RAM.

**Comment by mjgiarlo** [comment] 2017-11-16 17:40
Could be, @hydrosIII, though I might expect a different error in that case. Do you get the same routing-related error if you hit other URLs (other than the root URL)?

**Comment by hydrosIII** [comment] 2017-11-16 17:44
Mmm it is not a Ram issue, have just tested with 8G RAM VPS. SAme result. Exactly what other URLS to  hit?

**Comment by mjgiarlo** [comment] 2017-11-16 18:30
@hydrosIII You can try hitting `/account/sign_up` or `/users/sign_in`

**Comment by hydrosIII** [comment] 2017-11-19 22:10
@mjgiarlo , Strange behaviour, i get 404 in /account/sign_up i get a valid responde in /users/sign_in. I will procede with creating a userm and follow the instructions.

**Comment by mjgiarlo** [comment] 2017-11-20 16:39
@hydrosIII This is very strange indeed, and I have not been able to reproduce. I've also seen the latest builds of Hyku deploy successfully to AWS, so I'm thinking something else is at fault here. FWIW:

```
   workspace  hyku  2.4.1p111[hyku]  master  docker version
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:18 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:56 2017
 OS/Arch:      linux/amd64
 Experimental: false

   workspace  hyku  2.4.1p111[hyku]  master  docker-compose version
docker-compose version 1.17.1, build 6d101fb
docker-py version: 2.5.1
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```

**Comment by mjgiarlo** [comment] 2017-11-20 16:40
Any advice, @eefahy @cbeer @bbranan @jcoyne ?

**Comment by hydrosIII** [comment] 2017-11-20 19:31
Ok, i have just installed latest commit from 16 nov, and rebuilt the entire stack, same results. 
Here i post the versions. 
host: Debian 9, Stretch , Docker 8 G of Ram. 4CPU ( i Dont see any relevant information here, but  i share it to be as reproducible as possible)

Kernel Version: 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u5 (2017-09-19) x86_64 GNU/Linux

git commit: 7122d7b209253e9bedeef5238c062a0bcab9085b (fater the update of hyrax 2.0 16 nov.
also tried with : ffc3cae3a0768b86ce0b48f3893a1ffea4f14011 (23 oct)

Docker version: 

```
Client:
 Version:      17.10.0-ce
 API version:  1.33
 Go version:   go1.8.3
 Git commit:   f4ffd25
 Built:        Tue Oct 17 19:02:43 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.10.0-ce
 API version:  1.33 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   f4ffd25
 Built:        Tue Oct 17 19:01:22 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

docker compose:

```
docker-compose version 1.8.0, build unknown
docker-py version: 1.9.0
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
```
Commands used to build. 

```
docker-compose build
docker compose up -d 
```

**Comment by hydrosIII** [comment] 2017-11-20 22:22
Ok, just to make everything match, i downgraded everything to Debian Jessie, just to make sure I matched the exact versions of every library.

docker

Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:46 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:39:27 2017
 OS/Arch:      linux/amd64
 Experimental: false


docker-compose.

docker-compose version 1.17.1, build 6d101fb
docker-py version: 2.5.1
CPython version: 2.7.9
OpenSSL version: OpenSSL 1.0.1t  3 May 2016

Same thing.

**Comment by mjgiarlo** [comment] 2017-11-20 22:49
@hydrosIII Here's what I see:

```
docker-compose images
WARNING: The JAVA_OPTS variable is not set. Defaulting to a blank string.
      Container             Repository         Tag       Image Id      Size  
-----------------------------------------------------------------------------
hyku_app_1              hyku_app              latest   a475924fa7f8   2.39 GB
hyku_db_1               postgres              latest   ca3a55649cfc   257 MB 
hyku_db_migrate_1       hyku_app              latest   a475924fa7f8   2.39 GB
hyku_fcrepo_1           cbeer/fcrepo4         4.7      f7d9bbf48458   393 MB 
hyku_initialize_app_1   hyku_app              latest   a475924fa7f8   2.39 GB
hyku_lb_1               dockercloud/haproxy   1.5.3    6c37485a1407   38.5 MB
hyku_memcache_1         memcached             latest   6c32c12d9101   80 MB  
hyku_redis_1            redis                 3        a858478874d1   175 MB 
hyku_solr_1             solr                  latest   1a1515505797   490 MB 
hyku_web_1              hyku_app              latest   a475924fa7f8   2.39 GB
hyku_workers_1          hyku_app              latest   a475924fa7f8   2.39 GB
hyku_zoo1_1             zookeeper             latest   5291027d4199   136 MB 
hyku_zoo2_1             zookeeper             latest   5291027d4199   136 MB 
hyku_zoo3_1             zookeeper             latest   5291027d4199   136 MB 
```

I haven't modified any of the images.

**Comment by mjgiarlo** [comment] 2017-11-20 22:52
@hydrosIII You may also want to pull and try again after this PR is merged: https://github.com/samvera-labs/hyku/pull/1506

**Comment by hydrosIII** [comment] 2017-11-21 01:02
Strange, There is a lot of difference in disk space between the hyku_web. I think the PR is not helping. Let me test further.

**Comment by hydrosIII** [comment] 2017-11-21 01:29
I'm out of ideas, sttill the same behaviour, i suspect there is something in the build of hyku_web that changes, i see that the others container are mostly standard. And by standard i mean that are taken directly from the docker hub, for example the apache zookepeers. Also i dont see plausible  error in the postgresql database. The fedora container has the same checksum, so it cannot be that. 

So here is the history for 

```
docker image history hyku_web       

IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
8785c4a84b8a        About an hour ago   /bin/sh -c #(nop)  EXPOSE 3000/tcp              0B                  
a755049bd808        About an hour ago   /bin/sh -c bundle exec rake assets:precompile   15.7MB              
c6673ca8bc3f        About an hour ago   /bin/sh -c #(nop) ADD dir:d1a13659a0cc18bd...   14.2MB              
95726580078a        3 hours ago         /bin/sh -c bundle install                       302MB               
194b5a443a50        3 hours ago         /bin/sh -c #(nop) ADD file:9a65930bc16cccc...   23.5kB              
667dd3f1d2ab        3 hours ago         /bin/sh -c #(nop) ADD file:d2fee3022cc4e64...   2.8kB               
ebad35bed85e        3 hours ago         /bin/sh -c #(nop) WORKDIR /data                 0B                  
6665af28be4a        3 hours ago         /bin/sh -c mkdir /data                          0B                  
f8044edbd6dc        3 hours ago         /bin/sh -c mkdir -p /opt/fits &&     curl ...   310MB               
cfbc07e72470        3 hours ago         /bin/sh -c apt-get update -qq &&     apt-g...   680MB               
ffe8239a147c        12 months ago       /bin/sh -c #(nop)  CMD ["irb"]                  0B                  
<missing>           12 months ago       /bin/sh -c mkdir -p "$GEM_HOME" "$BUNDLE_B...   0B                  
<missing>           12 months ago       /bin/sh -c #(nop)  ENV PATH=/usr/local/bun...   0B                  
<missing>           12 months ago       /bin/sh -c #(nop)  ENV BUNDLE_PATH=/usr/lo...   0B                  
<missing>           12 months ago       /bin/sh -c #(nop)  ENV GEM_HOME=/usr/local...   0B                  
<missing>           12 months ago       /bin/sh -c gem install bundler --version "...   1.4MB               
<missing>           12 months ago       /bin/sh -c #(nop)  ENV BUNDLER_VERSION=1.13.6   0B                  
<missing>           12 months ago       /bin/sh -c set -ex   && buildDeps='   biso...   120MB               
<missing>           12 months ago       /bin/sh -c #(nop)  ENV RUBYGEMS_VERSION=2.6.8   0B                  
<missing>           12 months ago       /bin/sh -c #(nop)  ENV RUBY_DOWNLOAD_SHA25...   0B                  
<missing>           12 months ago       /bin/sh -c #(nop)  ENV RUBY_VERSION=2.3.1       0B                  
<missing>           12 months ago       /bin/sh -c #(nop)  ENV RUBY_MAJOR=2.3           0B                  
<missing>           12 months ago       /bin/sh -c mkdir -p /usr/local/etc  && {  ...   45B                 
<missing>           12 months ago       /bin/sh -c apt-get update && apt-get insta...   318MB               
<missing>           12 months ago       /bin/sh -c apt-get update && apt-get insta...   123MB               
<missing>           12 months ago       /bin/sh -c apt-get update && apt-get insta...   44.3MB              
<missing>           12 months ago       /bin/sh -c #(nop)  CMD ["/bin/bash"]            0B                  
<missing>           12 months ago       /bin/sh -c #(nop) ADD file:41ea5187c501168...   123MB   
```
@mjgiarlo So there is something that is pulling 500 Mb more in your setup.

**Comment by hydrosIII** [comment] 2017-11-21 03:41
This fork is working https://github.com/UCDavisLibrary/ucd-hyku

**Comment by mjgiarlo** [comment] 2017-11-21 17:52
@hydrosIII I'm seeing some differences near the top of the output:

```
$ docker image history hyku_web
IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
a475924fa7f8        19 hours ago        /bin/sh -c #(nop)  EXPOSE 3000/tcp              0B                  
97097f926a71        19 hours ago        /bin/sh -c bundle exec rake assets:precompile   29.1MB              
2e7546d9021a        19 hours ago        /bin/sh -c #(nop) ADD dir:0a2f1ff53b17c48f...   513MB               
b12f4c594631        19 hours ago        /bin/sh -c bundle install                       302MB               
82c07efb3e9b        19 hours ago        /bin/sh -c #(nop) ADD file:bcbca944372803d...   23.5kB        
...
```

**Comment by mjgiarlo** [comment] 2017-11-21 17:57
@hydrosIII Ah, I understand the difference now. It comes from this line:

https://github.com/samvera-labs/hyku/blob/master/Dockerfile#L14

And I have a bunch of stuff in my Hyku working directory that you likely don't, particularly in the `fcrepo4-data`, `log`, and `tmp` subdirectories. This may not be an interesting difference after all.

**Comment by mjgiarlo** [comment] 2017-11-21 17:58
@hydrosIII Glad to hear the UCD fork is working for you. If you gain any additional insight on why our docker configuration isn't working for you, I'm all ears.

**Comment by hydrosIII** [comment] 2017-11-21 18:57
@mjgiarlo But it is an important difference somehow.  I have tested this setup of hyku in at least 3 different computers with different OS, non of them working. If you take the plain repo and use docker-compose  to build something, i think the more likely output is to not work.  (no data, no nothing)

So that special /data folder is to add data to the hyku container that had been previously worked on? 

I think that is the purpose of a docker Volume.  I mean, the differences of hash in the container shoud come for example of the apt-get upgrade instructions, that can build different containers, with different library versions, but in theory they are just updates. The docker container should be as reproducible as possible. 

So regarding the Line in the DockerFile:

ADD . /data

Maybe change the docker-compose line  from 

```
   volumes:
      - app:/data/tmp/uploads
    networks:
      internal:
```
to 

```
   volumes:
      - app:/data/
    networks:
      internal:
```

Also there is a difference in the Solr Container of 200 Mb.

**Comment by mjgiarlo** [comment] 2017-11-21 19:22
@hydrosIII I cloned a fresh version of Hyku and still could not reproduce.

> Im just doing a:
> `git clone https://github.com/samvera-labs/hyku.git`
> and then
> `docker-compose build` 
> `docker-compose up -d`
> Wasn't that the intention of the repo?

Yep, that's the intention. Sorry it's not working for you.

**Comment by hydrosIII** [comment] 2017-11-21 19:45
Indeed very strange, I have used Arch linux ( last version, this is my laptop 4G RAM 4CPU) and Debian Jessie, Debian Stretch (VPS with 8G of RAM 4 CPU). Docker Versions, ranging from the 17.07 to 17.10. (changed them during the tests, to see if there was a docker problem). If you clone in your previously working setup you will be using the docker images that are already built in your system.

**Comment by mjgiarlo** [comment] 2017-11-21 20:23
@hydrosIII Thanks for all the work you've put into this. Happy to explore making changes to our docker config once I understand what is at fault.

**Comment by Xhycos** [comment] 2018-05-25 11:38
Hello @hydrosIII @mjgiarlo.
I try to install hyku on docker, inside a vagrant vm (almost identical to our vm productions). I install some dockered apps.. and worked.. But with your's, I have exactly the same problem than you.

I run beside a proxy. Do you have a proxy @hydrosIII ? 
I just had ENV HTTP_PROXY in Dockerfile to success to build the image. But when I run, same 404 than you, same accessible page (/users/sign_in) 

When I watch the log web container, I have 
```log
ActionController::RoutingError (Not Found):
app/controllers/application_controller.rb:27:in `block in <class:ApplicationController>'
AND
** [Honeybadger] Unable to send error report: API key is missing.
```
In db log, when it's start the first time in the beginning, I have just this 
```log
relation "sipity_roles" does not exist at character 566
SELECT (...)
 FROM pg_attribute a
LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum
LEFT JOIN pg_type t ON a.atttypid = t.oid
LEFT JOIN pg_collation c ON a.attcollation = c.oid AND a.attcollation <> t.typcollation
WHERE a.attrelid = '"sipity_roles"'::regclass
AND a.attnum > 0 AND NOT a.attisdropped
ORDER BY a.attnum
```

Did you find something?

Thanks you for you help.

**Comment by mjgiarlo** [comment] 2018-05-25 17:31
@Xhycos If you don't hear back here, you may want to jump on the Samvera slack workspace and ask this in the `#hyku` channel.

**Comment by orangewolf** [comment] 2018-06-02 01:03
@hydrosIII I'm thinking that the issue you are seeing with the routing error is actually a problem with Apartments (the multi tenant part).  You mention a proxy, and I'm betting that means you are accessing the site via a 3 part domain "your.domain.com" in some way.  When you do that, hyku things you want to see a specific non-existant account and fails. 

you can fix that by changing the config/settings.yml file
multitenancy:
  enabled: true
  default_host: SET THIS
  admin_host: SET THIS
  admin_only_tenant_creation: true

**Closed** 2018-06-12 12:22 UTC

**Comment by fishfree** [comment] 2019-04-09 08:18
The issue still remains.
