### ISSUE TITLE
Error adding user to group

### ISSUE THREAD

**Issue by bbranan** [samvera-labs/hyku#1187] opened 2017-06-01 17:15 UTC
Attempting to add a user to a group is resulting in an error. 

Steps to replicate:
1. Log in to a tenant as an admin
2. Go to Manage Groups, select "Edit group & users" on an existing group
3. Select the Users tab
4. Enter the ID of a user in the tenant, click "Add"

The error displayed on the UI was `You may have mistyped the address or the page may have moved.`

The page where the Add button was clicked: http://testtenant.pilot.hykudirect.org/admin/groups/1/users

The page it sent me to after Add button was clicked: http://testtenant.pilot.hykudirect.org/admin/groups/1/users/add?locale=en.

It doesn't look like Honeybadger captured this issue.

According to discussion on standup call on 6/1, the user ID field should not be displayed in the UI. The process of adding a user to a group should be:
- On the Users tab, type in the Search for User field
- Select the user that is displayed from the search result and click Add

**Comment by mjgiarlo** [comment] 2017-06-06 20:34
This should have been resolved with https://github.com/samvera-labs/hyku/pull/839, but I can now confirm that I am seeing the buggy behavior in AWS, docker-compose, and local deployments when `RAILS_ENV=production`. The JavaScript that is supposed to fire is in the compiled application.js, so the code is there, and I see no errors in the JavaScript console.

**Comment by darrenleeweber** [comment] 2017-06-14 18:25
Trying to replicate this in my hyku tenant at \

Steps to replicate:
1. Log in to a tenant as an admin
2. Go to Dashboard
3. Find the "CONFIGURATION" group in the sidebar and select "Users and groups"
4. Choose the "Manage groups" in the sidebar and create a new group
5. Once created, choose the "Edit group and users" under "Actions"
6. Select the Users tab
7. While trying to search for a user, it redirected to the user display and there was no way to get back; when using the browser back button, all the UI CSS got completely messed up.  (But that's a different issue.)  OK, so creater a new user and/or get a User-ID and go back to the dashboard to sorta start over.

4. Enter the ID of a user in the tenant, click "Add"

**Comment by mjgiarlo** [comment] 2017-06-14 18:53
@darrenleeweber If you spin up Hyku in `development` mode locally, you can see how it's supposed to look. The issue is that some hidden fields are not being hidden. See https://github.com/samvera-labs/hyku/pull/839 (fixed https://github.com/samvera-labs/hyku/issues/837) for prior work on this.

**Comment by mjgiarlo** [comment] 2017-06-14 18:54
AFAICT, this only fails in `production` mode, and that's key to this work.

**Comment by darrenleeweber** [comment] 2017-06-14 21:26
Confirmed that everything behaves as expect in dev-env.

Using firebug inspector, the div markup details are slightly different in prod vs. dev, i.e.

- prod
```html
<div class="panel-body">
    <form class="simple_form form-inline pull-left js-group-user-search" 
          action="/users?locale=en"
          accept-charset="UTF-8" method="get">
    <form class="simple_form form-inline pull-left js-group-user-add"
          action="/admin/groups/1/users/add?locale=en"
          accept-charset="UTF-8" method="post">
</div>
```

- dev
```html
<div class="panel-body">
    <form class="simple_form form-inline pull-left js-group-user-search" 
          action="/users?locale=en" 
          accept-charset="UTF-8" method="get">
    <form class="simple_form form-inline pull-left js-group-user-add" 
          action="/admin/groups/1/users/add?locale=en" 
          accept-charset="UTF-8" method="post" style="display: none;">
</div>
```

So the only difference in this markup is that `dev` has the user-add form hidden, using `style="display: none;"`.

**Comment by darrenleeweber** [comment] 2017-06-14 22:11
Files involved in this form include:
```sh
$ git grep -l 'js-group-user-add'
app/assets/javascripts/hyku/groups/add_member.js
app/views/admin/groups/users.html.erb
spec/features/admin_dashboard_spec.rb
spec/views/admin/groups/users.html.erb_spec.rb
```

**Comment by darrenleeweber** [comment] 2017-06-15 18:09
Struggled to get a prod-env running on my laptop to debug this problem.  Documented my solution in the wiki at https://github.com/samvera-labs/hyku/wiki/Hyku-Development-Guide#production-debugging-on-laptop

The chrome JS console reports an error in the compiled application.js file:
```
Uncaught Error: See almond README: incorrect module build, no module name
    at define (application-b2f35d1….js:24)
    at application-b2f35d1….js:29
    at application-b2f35d1….js:29
define @ application-b2f35d1….js:24
(anonymous) @ application-b2f35d1….js:29
(anonymous) @ application-b2f35d1….js:29
```

**Comment by darrenleeweber** [comment] 2017-06-15 18:12
This might be a red-herring, but the chrome JS console reports an error in the compiled application.js file:
```
Uncaught Error: See almond README: incorrect module build, no module name
    at define (application-b2f35d1….js:24)
    at application-b2f35d1….js:29
    at application-b2f35d1….js:29
define @ application-b2f35d1….js:24
(anonymous) @ application-b2f35d1….js:29
(anonymous) @ application-b2f35d1….js:29
```
I don't know what impact this is having on the performance of the JS script(s).

**Comment by jcoyne** [comment] 2017-06-15 18:39
I'm pretty certain that's a red herring.

**Comment by darrenleeweber** [comment] 2017-06-15 19:03
There's a JS error in `Hyrax.popovers()`, i.e.
```javascript
    popovers: function() {
        $("a[data-toggle=popover]").popover({  // this call to .popover is not a function
            html: !0
        }).click(function() {
            return !1
        })
    },
```
The JS stacktrace in the chrome console is
```
Uncaught TypeError: $(...).popover is not a function
    at Object.popovers (application-b2f35d1….js:formatted:35266)
    at Object.initialize (application-b2f35d1….js:formatted:35230)
    at application-b2f35d1….js:formatted:35321
    at Object.activate (application-b2f35d1….js:formatted:10867)
    at HTMLDocument.<anonymous> (application-b2f35d1….js:formatted:10877)
    at HTMLDocument.dispatch (application-b2f35d1….js:formatted:2629)
    at HTMLDocument.g.handle (application-b2f35d1….js:formatted:2561)
    at Object.t.dispatch (application-b2f35d1….js:formatted:8806)
    at n.t.Controller.n.notifyApplicationAfterPageLoad (application-b2f35d1….js:formatted:10309)
    at n.t.Controller.n.visitCompleted (application-b2f35d1….js:formatted:10340)
```

**Comment by jcoyne** [comment] 2017-06-15 19:13
@darrenleeweber that should be from bootstrap popovers: http://getbootstrap.com/javascript/#popovers  That may be missing from the javascript manifest.

**Comment by jcoyne** [comment] 2017-06-15 19:14
And this should be loaded here: https://github.com/samvera/hyrax/blob/master/app/assets/javascripts/hyrax.js#L16-L17

**Comment by darrenleeweber** [comment] 2017-06-15 20:18
Clueless about how to solve this exactly, because it appears the compressed application.js file does contain some `bs.popover` code.  It's possible there is a conflict in the included JS libs that only arises when the JS files are consolidated into one large file and compressed.
Related SO question:
- https://stackoverflow.com/questions/29910823/popover-is-not-a-function

**Closed** 2017-06-21 17:26 UTC
Labels: Blocker, bug, in progress, pilot, user interface
