### ISSUE TITLE
Problem with Universal Viewer

### ISSUE THREAD

**Issue by suso2** [samvera-labs/hyku#1301] opened 2017-06-27 10:51 UTC
Universal Viewer is not working on my instance (code updated today). I use docker 17.05.0-ce on ubuntu server 16.04.2 LTS. 
It seems it doesn't render images (png in my test case). Sometimes it shows "Not found" and sometimes it shows a spinning square.
I tried with firefox, chrome and Edge.

<img width="774" alt="2017-06-27_12-37-08" src="https://user-images.githubusercontent.com/7069866/27584132-26e68b6e-5b37-11e7-9450-a8d6f1471dc2.png">

**Comment by mjgiarlo** [comment] 2017-06-27 23:26
Thanks for submitting this issue, @suso2. We'll have a look. (A bunch of us are traveling abroad this week for a conference, so it may not be instantaneous.)

**Comment by jcoyne** [comment] 2017-06-28 00:08
I've also seen problems with PNGs.

**Comment by jcoyne** [comment] 2017-06-28 00:26
After a few moments my problem was resolved.  Is it possible the background job was not finished processing the file yet?

**Comment by suso2** [comment] 2017-06-28 07:40
@jcoyne, I don't think so. I've been waiting for an hour...
After reading your post I created a new work with only one image and I waited for ten minutes before refresh the page. No success with UV.
Thanks in advance.

**Comment by jcoyne** [comment] 2017-06-28 09:41
Are you getting messages in the logs similar to this issue? https://github.com/samvera-labs/hyku/issues/1274

**Comment by suso2** [comment] 2017-06-28 10:21
Yes, I am getting similar messages...
Anyway, now UV works fine with one work (one image) but it doesn't work with others works (four images).
(Do you want the complete docker-compose logs?)
Thanks

workers_1         | E, [2017-06-28T08:40:43.265496 #1] ERROR -- : [ActiveJob] [CharacterizeJob] [92e7acb6-ab1e-4073-9185-eac304a6a648] Error performing CharacterizeJob (Job ID: 92e7acb6-ab1e-4073-9185-eac304a6a648) from Sidekiq(default) in 1089.85ms: RuntimeError (Unable to execute command "/opt/fits-1.0.5/fits.sh -i "/data/tmp/uploads/718605f7-e184-4cc0-b61b-5fbd91e5c4b8/hyrax/uploaded_file/file/4/Elena_Martín_20150918_110435.jpg""
workers_1         | Exception in thread "main" edu.harvard.hul.ois.fits.exceptions.FitsToolException: Error loading native library for MediaInfo please check that fits_home is properly set
workers_1         | 	at edu.harvard.hul.ois.fits.tools.mediainfo.MediaInfo.<init>(MediaInfo.java:92)
workers_1         | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
workers_1         | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
workers_1         | 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
workers_1         | 	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
workers_1         | 	at java.lang.Class.newInstance(Class.java:383)
workers_1         | 	at edu.harvard.hul.ois.fits.tools.ToolBelt.init(ToolBelt.java:136)
workers_1         | 	at edu.harvard.hul.ois.fits.tools.ToolBelt.<init>(ToolBelt.java:72)
workers_1         | 	at edu.harvard.hul.ois.fits.Fits.<init>(Fits.java:239)
workers_1         | 	at edu.harvard.hul.ois.fits.Fits.<init>(Fits.java:121)
workers_1         | 	at edu.harvard.hul.ois.fits.Fits.<init>(Fits.java:110)
workers_1         | 	at edu.harvard.hul.ois.fits.Fits.main(Fits.java:290)

**Comment by jcoyne** [comment] 2017-06-28 23:44
Thanks for checking into that @suso2. I'm going to close this issue and say that it's a duplicate of #1274, okay? I suspect when we close that issue, you will see your problem resolved.

**Closed by jcoyne** 2017-06-28 23:44 UTC
