### ISSUE TITLE
Office documents should have thumbnails

### ISSUE THREAD

**Issue by mjgiarlo** [samvera-labs/hyku#1202] opened 2017-06-02 23:01 UTC
The thumbnails for office documents (tested with .ppt and .pptx) render as a broken image with the text "Default" within it. The thumbnail links look like https://troubleshooting.demo.hydrainabox.org/images/0c6e5278-9a68-4489-8745-e65f7dce8c98%2Ffiles%2F938ff88f-1030-410d-9679-38d55ca07e22/full/!150,300/0/default.jpg

I have seen this in both the docker and AWS builds. Have not tested this locally or in Hyrax.

**Comment by jcoyne** [comment] 2017-06-03 12:52
Seeing this on AWS:
```
RuntimeError: Unable to execute command "soffice --invisible --headless --convert-to pdf --outdir /tmp /var/app/current/tmp/uploads/83/09/2d/c2/83092dc2-22f0-4ddf-a72f-e06e36a3bc5c/83092dc2-22f0-4ddf-a72f-e06e36a3bc5c20170602-25338-1gjs6r5". Exit code: pid 2586 exit 77 Error message: [Java framework] Error in function createSettingsDocument (elements.cxx). javaldx failed! Warning: failed to read path from javaldx 
```

Apparently soffice needs a writable directory in which to write its configs.

**Comment by jcoyne** [comment] 2017-06-05 15:25
Duplicate of #1193?

**Comment by mjgiarlo** [comment] 2017-06-05 16:37
Yup. Moved our comments over to #1193. Closing.

**Closed** 2017-06-05 16:37 UTC
Labels: bug, demo, devops, docker, duplicate
